export const fav = [
  {
    id: "tailwind",
    name: "I Love Tailwind",
    image: "/images/icons/Tailwind.webp",
    width: 80,
    height: 45,
    class: "top-[120px] left-[375px]",
  },
  {
    id: "nest",
    name: "My Favorite Backend Framework",
    image: "/images/icons/Nest.webp",
    width: 70,
    height: 70,
    class: "top-[350px] left-[235px]",
  },
  {
    id: "ts",
    name: "Still learn",
    image: "/images/icons/Ts.webp",
    width: 70,
    height: 70,
    class: "top-[55px] left-[75px]",
  },
  {
    id: "js",
    name: "My Favorite Language",
    image: "/images/icons/Js.webp",
    width: 70,
    height: 70,
    class: "top-[15px] left-[215px]",
  },
  {
    id: "laravel",
    name: "First Love",
    image: "/images/icons/Laravel.webp",
    width: 70,
    height: 70,
    class: "top-[185px] left-[185px]",
  },

  {
    id: "Docker",
    name: "Make Everything Simple",
    image: "/images/icons/Docker.webp",
    width: 70,
    height: 70,
    class: "top-[225px] left-[455px]",
  },
  {
    id: "vite",
    name: "Basic and Fast",
    image: "/images/icons/Vite.webp",
    width: 70,
    height: 70,
    class: "top-[35px] left-[545px]",
  },
  {
    id: "next",
    name: "Most Powefull Today",
    image: "/images/icons/NextJs.webp",
    width: 70,
    height: 70,
    class: "top-[335px] left-[515px]",
  },
  {
    id: "rq",
    name: "Easy to Fetch Data",
    image: "/images/icons/ReactQuery.webp",
    width: 70,
    height: 70,
    class: "top-[285px] left-[65px]",
  },
];
